# Generated by Django 2.1.7 on 2019-04-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_equip', models.CharField(max_length=100)),
                ('num_of_items', models.IntegerField(null=True)),
                ('siz', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('function_or_not', models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], max_length=15)),
                ('equip_picture', models.CharField(max_length=1000, null=True)),
                ('user_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_equipment', models.CharField(max_length=100)),
                ('number_of_items', models.IntegerField()),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('functional_or_not', models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Non-Functional', 'Non-Functional')], max_length=15)),
                ('equipment_picture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_equipment', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('type_of_equipment_picture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentType'),
        ),
    ]
