# Generated by Django 2.1.6 on 2019-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('Bio', 'Biology'), ('CS', 'Computer Science'), ('Math', 'Mathematics'), ('PS', 'Political Science'), ('Psych', 'Psychology'), ('Comm', 'Communications'), ('FA', 'Fine Arts'), ('Mgt', 'Management')], default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_lvl',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='none', max_length=2),
            preserve_default=False,
        ),
    ]
