# Generated by Django 2.1.7 on 2019-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_class_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Communications', 'Communications'), ('Fine Arts', 'Fine Arts'), ('Management', 'Management')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_lvl',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=20),
        ),
    ]
