# Generated by Django 2.1.6 on 2019-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=255)),
                ('num_borrowed', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
