# Generated by Django 2.1.6 on 2019-04-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20190424_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='num_borrowed',
            field=models.IntegerField(null=True),
        ),
    ]
