# Generated by Django 2.1.6 on 2019-04-24 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190424_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
