# Generated by Django 2.1.6 on 2019-04-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_b',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
