# Generated by Django 2.1.6 on 2019-04-06 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20190406_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
