# Generated by Django 2.1.6 on 2019-03-11 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('c_title', models.CharField(max_length=50)),
                ('c_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('student_number', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('s_number', models.CharField(max_length=20, null=True)),
                ('contact_no', models.CharField(max_length=11)),
                ('email_add', models.CharField(max_length=100)),
                ('s_course', models.CharField(choices=[('Bio', 'Biology'), ('CS', 'Computer Science'), ('Math', 'Mathematics'), ('PS', 'Political Science'), ('Psych', 'Psychology'), ('Comm', 'Communications'), ('FA', 'Fine Arts'), ('Mgt', 'Management')], max_length=100)),
                ('s_year_lvl', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
            ],
        ),
    ]
